#pragma once
#include <rlutil/rlutilJM.h>
int** PlayerSprite1()
{
	try
	{
		int** sprite = rlUtilJM::InitSpriteArray(23, 25);
		for (int i = 0; i < 23; i++) {
			for (int j = 0; j < 25; j++) {
				rlUtilJM::AddPixel(i, j, EMPTY, sprite);
			}
		}

		rlUtilJM::AddPixel(0, 2, CHARACTER1, sprite);
		rlUtilJM::AddPixel(0, 3, CHARACTER1, sprite);
		rlUtilJM::AddPixel(0, 4, CHARACTER1, sprite);
		rlUtilJM::AddPixel(0, 5, CHARACTER1, sprite);
		rlUtilJM::AddPixel(0, 6, CHARACTER1, sprite);
		rlUtilJM::AddPixel(0, 7, CHARACTER1, sprite);
		rlUtilJM::AddPixel(0, 8, CHARACTER1, sprite);
		rlUtilJM::AddPixel(0, 15, CHARACTER1, sprite);
		rlUtilJM::AddPixel(0, 16, CHARACTER1, sprite);
		rlUtilJM::AddPixel(0, 17, CHARACTER1, sprite);
		rlUtilJM::AddPixel(0, 18, CHARACTER1, sprite);
		rlUtilJM::AddPixel(0, 19, CHARACTER1, sprite);
		rlUtilJM::AddPixel(0, 20, CHARACTER1, sprite);
		rlUtilJM::AddPixel(0, 21, CHARACTER1, sprite);
		rlUtilJM::AddPixel(1, 2, CHARACTER1, sprite);
		rlUtilJM::AddPixel(1, 3, CHARACTER1, sprite);
		rlUtilJM::AddPixel(1, 4, CHARACTER1, sprite);
		rlUtilJM::AddPixel(1, 5, CHARACTER1, sprite);
		rlUtilJM::AddPixel(1, 6, CHARACTER1, sprite);
		rlUtilJM::AddPixel(1, 7, CHARACTER1, sprite);
		rlUtilJM::AddPixel(1, 8, CHARACTER1, sprite);
		rlUtilJM::AddPixel(1, 9, CHARACTER1, sprite);
		rlUtilJM::AddPixel(1, 14, CHARACTER1, sprite);
		rlUtilJM::AddPixel(1, 15, CHARACTER1, sprite);
		rlUtilJM::AddPixel(1, 16, CHARACTER1, sprite);
		rlUtilJM::AddPixel(1, 17, CHARACTER1, sprite);
		rlUtilJM::AddPixel(1, 18, CHARACTER1, sprite);
		rlUtilJM::AddPixel(1, 19, CHARACTER1, sprite);
		rlUtilJM::AddPixel(1, 20, CHARACTER1, sprite);
		rlUtilJM::AddPixel(1, 21, CHARACTER1, sprite);
		rlUtilJM::AddPixel(1, 22, CHARACTER1, sprite);
		rlUtilJM::AddPixel(2, 1, CHARACTER1, sprite);
		rlUtilJM::AddPixel(2, 2, CHARACTER1, sprite);
		rlUtilJM::AddPixel(2, 3, CHARACTER1, sprite);
		rlUtilJM::AddPixel(2, 4, CHARACTER1, sprite);
		rlUtilJM::AddPixel(2, 5, CHARACTER1, sprite);
		rlUtilJM::AddPixel(2, 6, CHARACTER1, sprite);
		rlUtilJM::AddPixel(2, 7, CHARACTER1, sprite);
		rlUtilJM::AddPixel(2, 8, CHARACTER1, sprite);
		rlUtilJM::AddPixel(2, 9, CHARACTER1, sprite);
		rlUtilJM::AddPixel(2, 10, CHARACTER1, sprite);
		rlUtilJM::AddPixel(2, 13, CHARACTER1, sprite);
		rlUtilJM::AddPixel(2, 14, CHARACTER1, sprite);
		rlUtilJM::AddPixel(2, 15, CHARACTER1, sprite);
		rlUtilJM::AddPixel(2, 16, CHARACTER1, sprite);
		rlUtilJM::AddPixel(2, 17, CHARACTER1, sprite);
		rlUtilJM::AddPixel(2, 18, CHARACTER1, sprite);
		rlUtilJM::AddPixel(2, 19, CHARACTER1, sprite);
		rlUtilJM::AddPixel(2, 20, CHARACTER1, sprite);
		rlUtilJM::AddPixel(2, 21, CHARACTER1, sprite);
		rlUtilJM::AddPixel(2, 22, CHARACTER1, sprite);
		rlUtilJM::AddPixel(2, 23, CHARACTER1, sprite);
		rlUtilJM::AddPixel(3, 1, CHARACTER1, sprite);
		rlUtilJM::AddPixel(3, 2, CHARACTER1, sprite);
		rlUtilJM::AddPixel(3, 3, CHARACTER1, sprite);
		rlUtilJM::AddPixel(3, 4, CHARACTER1, sprite);
		rlUtilJM::AddPixel(3, 5, CHARACTER1, sprite);
		rlUtilJM::AddPixel(3, 6, CHARACTER1, sprite);
		rlUtilJM::AddPixel(3, 7, CHARACTER1, sprite);
		rlUtilJM::AddPixel(3, 8, CHARACTER1, sprite);
		rlUtilJM::AddPixel(3, 9, CHARACTER1, sprite);
		rlUtilJM::AddPixel(3, 10, CHARACTER1, sprite);
		rlUtilJM::AddPixel(3, 13, CHARACTER1, sprite);
		rlUtilJM::AddPixel(3, 14, CHARACTER1, sprite);
		rlUtilJM::AddPixel(3, 15, CHARACTER1, sprite);
		rlUtilJM::AddPixel(3, 16, CHARACTER1, sprite);
		rlUtilJM::AddPixel(3, 17, CHARACTER1, sprite);
		rlUtilJM::AddPixel(3, 18, CHARACTER1, sprite);
		rlUtilJM::AddPixel(3, 19, CHARACTER1, sprite);
		rlUtilJM::AddPixel(3, 20, CHARACTER1, sprite);
		rlUtilJM::AddPixel(3, 21, CHARACTER1, sprite);
		rlUtilJM::AddPixel(3, 22, CHARACTER1, sprite);
		rlUtilJM::AddPixel(3, 23, CHARACTER1, sprite);

		rlUtilJM::AddPixel(4, 1, CHARACTER1, sprite);
		rlUtilJM::AddPixel(4, 2, CHARACTER1, sprite);
		rlUtilJM::AddPixel(4, 3, CHARACTER1, sprite);
		rlUtilJM::AddPixel(4, 4, CHARACTER1, sprite);
		rlUtilJM::AddPixel(4, 5, CHARACTER1, sprite);
		rlUtilJM::AddPixel(4, 6, CHARACTER1, sprite);
		rlUtilJM::AddPixel(4, 7, CHARACTER1, sprite);
		rlUtilJM::AddPixel(4, 8, CHARACTER1, sprite);
		rlUtilJM::AddPixel(4, 9, CHARACTER1, sprite);
		rlUtilJM::AddPixel(4, 10, CHARACTER1, sprite);
		rlUtilJM::AddPixel(4, 13, CHARACTER1, sprite);
		rlUtilJM::AddPixel(4, 14, CHARACTER1, sprite);
		rlUtilJM::AddPixel(4, 15, CHARACTER1, sprite);
		rlUtilJM::AddPixel(4, 16, CHARACTER1, sprite);
		rlUtilJM::AddPixel(4, 17, CHARACTER1, sprite);
		rlUtilJM::AddPixel(4, 18, CHARACTER1, sprite);
		rlUtilJM::AddPixel(4, 19, CHARACTER1, sprite);
		rlUtilJM::AddPixel(4, 20, CHARACTER1, sprite);
		rlUtilJM::AddPixel(4, 21, CHARACTER1, sprite);
		rlUtilJM::AddPixel(4, 22, CHARACTER1, sprite);
		rlUtilJM::AddPixel(4, 23, CHARACTER1, sprite);

		rlUtilJM::AddPixel(5, 1, CHARACTER1, sprite);
		rlUtilJM::AddPixel(5, 2, CHARACTER1, sprite);
		rlUtilJM::AddPixel(5, 3, CHARACTER1, sprite);
		rlUtilJM::AddPixel(5, 4, CHARACTER1, sprite);
		rlUtilJM::AddPixel(5, 5, CHARACTER1, sprite);
		rlUtilJM::AddPixel(5, 6, CHARACTER1, sprite);
		rlUtilJM::AddPixel(5, 7, CHARACTER1, sprite);
		rlUtilJM::AddPixel(5, 8, CHARACTER1, sprite);
		rlUtilJM::AddPixel(5, 9, CHARACTER1, sprite);
		rlUtilJM::AddPixel(5, 10, CHARACTER1, sprite);
		rlUtilJM::AddPixel(5, 11, CHARACTER1, sprite);
		rlUtilJM::AddPixel(5, 12, CHARACTER1, sprite);
		rlUtilJM::AddPixel(5, 13, CHARACTER1, sprite);
		rlUtilJM::AddPixel(5, 14, CHARACTER1, sprite);
		rlUtilJM::AddPixel(5, 15, CHARACTER1, sprite);
		rlUtilJM::AddPixel(5, 16, CHARACTER1, sprite);
		rlUtilJM::AddPixel(5, 17, CHARACTER1, sprite);
		rlUtilJM::AddPixel(5, 18, CHARACTER1, sprite);
		rlUtilJM::AddPixel(5, 19, CHARACTER1, sprite);
		rlUtilJM::AddPixel(5, 20, CHARACTER1, sprite);
		rlUtilJM::AddPixel(5, 21, CHARACTER1, sprite);
		rlUtilJM::AddPixel(5, 22, CHARACTER1, sprite);
		rlUtilJM::AddPixel(5, 23, CHARACTER1, sprite);

		rlUtilJM::AddPixel(6, 1, CHARACTER1, sprite);
		rlUtilJM::AddPixel(6, 2, CHARACTER1, sprite);
		rlUtilJM::AddPixel(6, 3, CHARACTER1, sprite);
		rlUtilJM::AddPixel(6, 4, CHARACTER1, sprite);
		rlUtilJM::AddPixel(6, 5, CHARACTER1, sprite);
		rlUtilJM::AddPixel(6, 6, CHARACTER1, sprite);
		rlUtilJM::AddPixel(6, 7, CHARACTER1, sprite);
		rlUtilJM::AddPixel(6, 8, CHARACTER1, sprite);
		rlUtilJM::AddPixel(6, 9, CHARACTER1, sprite);
		rlUtilJM::AddPixel(6, 10, CHARACTER1, sprite);
		rlUtilJM::AddPixel(6, 11, CHARACTER1, sprite);
		rlUtilJM::AddPixel(6, 12, CHARACTER1, sprite);
		rlUtilJM::AddPixel(6, 13, CHARACTER1, sprite);
		rlUtilJM::AddPixel(6, 14, CHARACTER1, sprite);
		rlUtilJM::AddPixel(6, 15, CHARACTER1, sprite);
		rlUtilJM::AddPixel(6, 16, CHARACTER1, sprite);
		rlUtilJM::AddPixel(6, 17, CHARACTER1, sprite);
		rlUtilJM::AddPixel(6, 18, CHARACTER1, sprite);
		rlUtilJM::AddPixel(6, 19, CHARACTER1, sprite);
		rlUtilJM::AddPixel(6, 20, CHARACTER1, sprite);
		rlUtilJM::AddPixel(6, 21, CHARACTER1, sprite);
		rlUtilJM::AddPixel(6, 22, CHARACTER1, sprite);
		rlUtilJM::AddPixel(6, 23, CHARACTER1, sprite);

		rlUtilJM::AddPixel(7, 1, CHARACTER1, sprite);
		rlUtilJM::AddPixel(7, 2, CHARACTER1, sprite);
		rlUtilJM::AddPixel(7, 3, CHARACTER1, sprite);
		rlUtilJM::AddPixel(7, 4, CHARACTER1, sprite);
		rlUtilJM::AddPixel(7, 5, CHARACTER1, sprite);
		rlUtilJM::AddPixel(7, 6, CHARACTER1, sprite);
		rlUtilJM::AddPixel(7, 7, CHARACTER1, sprite);
		rlUtilJM::AddPixel(7, 8, CHARACTER1, sprite);
		rlUtilJM::AddPixel(7, 9, CHARACTER1, sprite);
		rlUtilJM::AddPixel(7, 10, CHARACTER1, sprite);
		rlUtilJM::AddPixel(7, 11, CHARACTER1, sprite);
		rlUtilJM::AddPixel(7, 12, CHARACTER1, sprite);
		rlUtilJM::AddPixel(7, 13, CHARACTER1, sprite);
		rlUtilJM::AddPixel(7, 14, CHARACTER1, sprite);
		rlUtilJM::AddPixel(7, 15, CHARACTER1, sprite);
		rlUtilJM::AddPixel(7, 16, CHARACTER1, sprite);
		rlUtilJM::AddPixel(7, 17, CHARACTER1, sprite);
		rlUtilJM::AddPixel(7, 18, CHARACTER1, sprite);
		rlUtilJM::AddPixel(7, 19, CHARACTER1, sprite);
		rlUtilJM::AddPixel(7, 20, CHARACTER1, sprite);
		rlUtilJM::AddPixel(7, 21, CHARACTER1, sprite);
		rlUtilJM::AddPixel(7, 22, CHARACTER1, sprite);
		rlUtilJM::AddPixel(7, 23, CHARACTER1, sprite);

		rlUtilJM::AddPixel(8, 2, CHARACTER1, sprite);
		rlUtilJM::AddPixel(8, 3, CHARACTER1, sprite);
		rlUtilJM::AddPixel(8, 4, CHARACTER1, sprite);
		rlUtilJM::AddPixel(8, 5, CHARACTER1, sprite);
		rlUtilJM::AddPixel(8, 6, CHARACTER1, sprite);
		rlUtilJM::AddPixel(8, 7, CHARACTER1, sprite);
		rlUtilJM::AddPixel(8, 8, CHARACTER1, sprite);
		rlUtilJM::AddPixel(8, 9, CHARACTER1, sprite);
		rlUtilJM::AddPixel(8, 10, CHARACTER1, sprite);
		rlUtilJM::AddPixel(8, 11, CHARACTER1, sprite);
		rlUtilJM::AddPixel(8, 12, CHARACTER1, sprite);
		rlUtilJM::AddPixel(8, 13, CHARACTER1, sprite);
		rlUtilJM::AddPixel(8, 14, CHARACTER1, sprite);
		rlUtilJM::AddPixel(8, 15, CHARACTER1, sprite);
		rlUtilJM::AddPixel(8, 16, CHARACTER1, sprite);
		rlUtilJM::AddPixel(8, 17, CHARACTER1, sprite);
		rlUtilJM::AddPixel(8, 18, CHARACTER1, sprite);
		rlUtilJM::AddPixel(8, 19, CHARACTER1, sprite);
		rlUtilJM::AddPixel(8, 20, CHARACTER1, sprite);
		rlUtilJM::AddPixel(8, 21, CHARACTER1, sprite);
		rlUtilJM::AddPixel(8, 22, CHARACTER1, sprite);

		rlUtilJM::AddPixel(9, 3, CHARACTER1, sprite);
		rlUtilJM::AddPixel(9, 4, CHARACTER1, sprite);
		rlUtilJM::AddPixel(9, 5, CHARACTER1, sprite);
		rlUtilJM::AddPixel(9, 6, CHARACTER1, sprite);
		rlUtilJM::AddPixel(9, 7, CHARACTER1, sprite);
		rlUtilJM::AddPixel(9, 8, CHARACTER1, sprite);
		rlUtilJM::AddPixel(9, 9, CHARACTER1, sprite);
		rlUtilJM::AddPixel(9, 10, CHARACTER1, sprite);
		rlUtilJM::AddPixel(9, 11, CHARACTER1, sprite);
		rlUtilJM::AddPixel(9, 12, CHARACTER1, sprite);
		rlUtilJM::AddPixel(9, 13, CHARACTER1, sprite);
		rlUtilJM::AddPixel(9, 14, CHARACTER1, sprite);
		rlUtilJM::AddPixel(9, 15, CHARACTER1, sprite);
		rlUtilJM::AddPixel(9, 16, CHARACTER1, sprite);
		rlUtilJM::AddPixel(9, 17, CHARACTER1, sprite);
		rlUtilJM::AddPixel(9, 18, CHARACTER1, sprite);
		rlUtilJM::AddPixel(9, 19, CHARACTER1, sprite);
		rlUtilJM::AddPixel(9, 20, CHARACTER1, sprite);
		rlUtilJM::AddPixel(9, 21, CHARACTER1, sprite);

		rlUtilJM::AddPixel(10, 4, CHARACTER1, sprite);
		rlUtilJM::AddPixel(10, 5, CHARACTER1, sprite);
		rlUtilJM::AddPixel(10, 6, CHARACTER1, sprite);
		rlUtilJM::AddPixel(10, 7, CHARACTER1, sprite);
		rlUtilJM::AddPixel(10, 8, CHARACTER1, sprite);
		rlUtilJM::AddPixel(10, 9, CHARACTER1, sprite);
		rlUtilJM::AddPixel(10, 10, CHARACTER2, sprite);
		rlUtilJM::AddPixel(10, 11, CHARACTER1, sprite);
		rlUtilJM::AddPixel(10, 12, CHARACTER1, sprite);
		rlUtilJM::AddPixel(10, 13, CHARACTER1, sprite);
		rlUtilJM::AddPixel(10, 14, CHARACTER2, sprite);
		rlUtilJM::AddPixel(10, 15, CHARACTER1, sprite);
		rlUtilJM::AddPixel(10, 16, CHARACTER1, sprite);
		rlUtilJM::AddPixel(10, 17, CHARACTER1, sprite);
		rlUtilJM::AddPixel(10, 18, CHARACTER1, sprite);
		rlUtilJM::AddPixel(10, 19, CHARACTER1, sprite);
		rlUtilJM::AddPixel(10, 20, CHARACTER1, sprite);

		rlUtilJM::AddPixel(11, 5, CHARACTER1, sprite);
		rlUtilJM::AddPixel(11, 6, CHARACTER1, sprite);
		rlUtilJM::AddPixel(11, 7, CHARACTER2, sprite);
		rlUtilJM::AddPixel(11, 8, CHARACTER1, sprite);
		rlUtilJM::AddPixel(11, 9, CHARACTER1, sprite);
		rlUtilJM::AddPixel(11, 10, CHARACTER1, sprite);
		rlUtilJM::AddPixel(11, 11, CHARACTER2, sprite);
		rlUtilJM::AddPixel(11, 12, CHARACTER3, sprite);
		rlUtilJM::AddPixel(11, 13, CHARACTER4, sprite);
		rlUtilJM::AddPixel(11, 14, CHARACTER1, sprite);
		rlUtilJM::AddPixel(11, 15, CHARACTER1, sprite);
		rlUtilJM::AddPixel(11, 16, CHARACTER2, sprite);
		rlUtilJM::AddPixel(11, 17, CHARACTER1, sprite);
		rlUtilJM::AddPixel(11, 18, CHARACTER1, sprite);
		rlUtilJM::AddPixel(11, 19, CHARACTER1, sprite);

		rlUtilJM::AddPixel(12, 6, CHARACTER1, sprite);
		rlUtilJM::AddPixel(12, 7, CHARACTER1, sprite);
		rlUtilJM::AddPixel(12, 8, CHARACTER1, sprite);
		rlUtilJM::AddPixel(12, 9, CHARACTER1, sprite);
		rlUtilJM::AddPixel(12, 10, CHARACTER1, sprite);
		rlUtilJM::AddPixel(12, 11, CHARACTER1, sprite);
		rlUtilJM::AddPixel(12, 12, CHARACTER1, sprite);
		rlUtilJM::AddPixel(12, 13, CHARACTER1, sprite);
		rlUtilJM::AddPixel(12, 14, CHARACTER1, sprite);
		rlUtilJM::AddPixel(12, 15, CHARACTER1, sprite);
		rlUtilJM::AddPixel(12, 16, CHARACTER1, sprite);
		rlUtilJM::AddPixel(12, 17, CHARACTER1, sprite);
		rlUtilJM::AddPixel(12, 18, CHARACTER1, sprite);

		rlUtilJM::AddPixel(13, 7, CHARACTER1, sprite);
		rlUtilJM::AddPixel(13, 8, CHARACTER1, sprite);
		rlUtilJM::AddPixel(13, 9, CHARACTER1, sprite);
		rlUtilJM::AddPixel(13, 10, CHARACTER1, sprite);
		rlUtilJM::AddPixel(13, 11, CHARACTER1, sprite);
		rlUtilJM::AddPixel(13, 12, CHARACTER1, sprite);
		rlUtilJM::AddPixel(13, 13, CHARACTER1, sprite);
		rlUtilJM::AddPixel(13, 14, CHARACTER1, sprite);
		rlUtilJM::AddPixel(13, 15, CHARACTER1, sprite);
		rlUtilJM::AddPixel(13, 16, CHARACTER1, sprite);
		rlUtilJM::AddPixel(13, 17, CHARACTER1, sprite);

		rlUtilJM::AddPixel(14, 8, CHARACTER1, sprite);
		rlUtilJM::AddPixel(14, 9, CHARACTER1, sprite);
		rlUtilJM::AddPixel(14, 10, CHARACTER1, sprite);
		rlUtilJM::AddPixel(14, 11, CHARACTER1, sprite);
		rlUtilJM::AddPixel(14, 12, CHARACTER1, sprite);
		rlUtilJM::AddPixel(14, 13, CHARACTER1, sprite);
		rlUtilJM::AddPixel(14, 14, CHARACTER1, sprite);
		rlUtilJM::AddPixel(14, 15, CHARACTER1, sprite);
		rlUtilJM::AddPixel(14, 16, CHARACTER1, sprite);

		rlUtilJM::AddPixel(15, 9, CHARACTER1, sprite);
		rlUtilJM::AddPixel(15, 10, CHARACTER1, sprite);
		rlUtilJM::AddPixel(15, 11, CHARACTER1, sprite);
		rlUtilJM::AddPixel(15, 12, CHARACTER1, sprite);
		rlUtilJM::AddPixel(15, 13, CHARACTER1, sprite);
		rlUtilJM::AddPixel(15, 14, CHARACTER1, sprite);
		rlUtilJM::AddPixel(15, 15, CHARACTER1, sprite);

		rlUtilJM::AddPixel(16, 10, CHARACTER1, sprite);
		rlUtilJM::AddPixel(16, 11, CHARACTER1, sprite);
		rlUtilJM::AddPixel(16, 12, CHARACTER1, sprite);
		rlUtilJM::AddPixel(16, 13, CHARACTER1, sprite);
		rlUtilJM::AddPixel(16, 14, CHARACTER1, sprite);

		rlUtilJM::AddPixel(17, 11, CHARACTER1, sprite);
		rlUtilJM::AddPixel(17, 12, CHARACTER1, sprite);
		rlUtilJM::AddPixel(17, 13, CHARACTER1, sprite);

		rlUtilJM::AddPixel(18, 12, CHARACTER1, sprite);
		return sprite;
	}
	catch (...) {}
};